import "./globals.css";
import type { Metadata } from "next";
import { AppProvider } from "./provider";
import { Montserrat } from "next/font/google";

export const metadata: Metadata = {
  title: "socialmotion",
  description: "Generated by socialmotion",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.variable} suppressHydrationWarning={true}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
